import requests

url = "<MORPHEUS_APPLIANCE_URL>/api/library/option-type-forms"                                     # change me :)

querystring = {"":""}

payload = {"optionTypeForm": {
    "name": "New Test Form",
    "description": "A simple test form",
    "code": "new_test_form",
    "config": {},
    "context": None,
    "isLocked": False,
    "labels": "",
    "fieldGroups": [
        {
            "name": "Layout, Plan, and Virtual Image Configuration",
            "code": "step-1",
            "description": None,
            "localizedName": None,
            "collapsible": False,
            "defaultCollapsed": False,
            "visibleOnCode": None,
            "options": [
                {
                    "name": "Layout",
                    "description": None,
                    "code": "layout_selector",
                    "excludeFromSearch": False,
                    "fieldName": "layout_selection_",
                    "fieldLabel": "Layout:",
                    "fieldCode": None,
                    "refCode": "layout_selector",
                    "fieldContext": "config.customOptions",
                    "fieldGroup": None,
                    "fieldClass": None,
                    "fieldAddOn": None,
                    "fieldComponent": None,
                    "fieldInput": None,
                    "placeHolder": None,
                    "verifyPattern": None,
                    "helpBlock": None,
                    "helpBlockFieldCode": None,
                    "defaultValue": None,
                    "optionSource": None,
                    "optionSourceType": None,
                    "optionList": None,
                    "type": "layout",
                    "advanced": False,
                    "required": False,
                    "exportMeta": False,
                    "editable": False,
                    "creatable": True,
                    "config": {
                        "groupField": "group_selector",
                        "cloudField": "cloud_selector",
                        "addonPosition": "",
                        "addon": "",
                        "instanceTypeCode": "ueqbal-windows",
                        "cloudId": "",
                        "groupId": "",
                        "instanceTypeFieldCode": "",
                        "cloudFieldType": "field",
                        "groupFieldType": "field",
                        "instanceTypeFieldType": "value"
                    },
                    "displayOrder": 0,
                    "wrapperClass": None,
                    "enabled": True,
                    "noBlank": False,
                    "dependsOnCode": None,
                    "visibleOnCode": None,
                    "requireOnCode": None,
                    "contextualDefault": False,
                    "displayValueOnDetails": False,
                    "showOnCreate": True,
                    "showOnEdit": True,
                    "localCredential": False,
                    "formField": True,
                    "isHidden": False,
                    "isLocked": False,
                    "minVal": None,
                    "maxVal": None
                },
                {
                    "name": "Plan",
                    "description": None,
                    "code": "plan_selector",
                    "excludeFromSearch": False,
                    "fieldName": "plan_selection_",
                    "fieldLabel": "Plan:",
                    "fieldCode": None,
                    "refCode": "plan_selector",
                    "fieldContext": "config.customOptions",
                    "fieldGroup": None,
                    "fieldClass": None,
                    "fieldAddOn": None,
                    "fieldComponent": None,
                    "fieldInput": None,
                    "placeHolder": None,
                    "verifyPattern": None,
                    "helpBlock": None,
                    "helpBlockFieldCode": None,
                    "defaultValue": None,
                    "optionSource": None,
                    "optionSourceType": None,
                    "optionList": None,
                    "type": "plan",
                    "advanced": False,
                    "required": False,
                    "exportMeta": False,
                    "editable": False,
                    "creatable": True,
                    "config": {
                        "poolFieldType": "field",
                        "poolField": "resourcePool_selector",
                        "defaultValue": "{}",
                        "groupId": "",
                        "groupFieldType": "field",
                        "layoutId": "",
                        "groupField": "group_selector",
                        "layoutField": "layout_selector",
                        "showPricing": False,
                        "cloudField": "cloud_selector",
                        "cloudId": "",
                        "diskField": "",
                        "poolId": "",
                        "cloudFieldType": "field",
                        "layoutFieldType": "field"
                    },
                    "displayOrder": 1,
                    "wrapperClass": None,
                    "enabled": True,
                    "noBlank": False,
                    "dependsOnCode": None,
                    "visibleOnCode": None,
                    "requireOnCode": None,
                    "contextualDefault": False,
                    "displayValueOnDetails": False,
                    "showOnCreate": True,
                    "showOnEdit": True,
                    "localCredential": False,
                    "formField": True,
                    "isHidden": False,
                    "isLocked": False,
                    "minVal": None,
                    "maxVal": None
                },
                {
            "name": "d326a1d4-ee83-49bc-b5eb-7a50f8b45b1b",
            "description": None,
            "code": "d326a1d4-ee83-49bc-b5eb-7a50f8b45b1b",
            "excludeFromSearch": False,
            "fieldName": "virtualImageSelector",
            "fieldLabel": "Virtual Image:",
            "fieldCode": None,
            "refCode": "d326a1d4-ee83-49bc-b5eb-7a50f8b45b1b",
            "fieldContext": "config.customOptions",
            "fieldGroup": None,
            "fieldClass": None,
            "fieldAddOn": None,
            "fieldComponent": None,
            "fieldInput": None,
            "placeHolder": None,
            "verifyPattern": None,
            "helpBlock": None,
            "helpBlockFieldCode": None,
            "defaultValue": None,
            "optionSource": None,
            "optionSourceType": None,
            "optionList": None,
            "type": "virtual-image",
            "advanced": False,
            "required": False,
            "exportMeta": False,
            "editable": False,
            "creatable": True,
            "config": {
              "cloudField": "cloud_selector",
              "addon": "",
              "addonPosition": "",
              "cloudId": "",
              "cloudFieldType": "cloud"
            },
            "displayOrder": 2,
            "wrapperClass": None,
            "enabled": True,
            "noBlank": False,
            "dependsOnCode": None,
            "visibleOnCode": None,
            "requireOnCode": None,
            "contextualDefault": False,
            "displayValueOnDetails": False,
            "showOnCreate": True,
            "showOnEdit": True,
            "localCredential": False,
            "formField": True,
            "isHidden": False,
            "isLocked": False,
            "minVal": None,
            "maxVal": None
          }
        ]
      }
            ]
        },
        {
            "name": "Storage configuration",
            "code": "87c9e32f-831b-4cc5-81c5-34fe737cec95",
            "description": None,
            "localizedName": None,
            "collapsible": False,
            "defaultCollapsed": False,
            "visibleOnCode": None,
            "options": [
                {
                    "name": "Disk",
                    "description": None,
                    "code": "disk_selector",
                    "excludeFromSearch": False,
                    "fieldName": "diskSelector",
                    "fieldLabel": "DisK:",
                    "fieldCode": None,
                    "refCode": "disk_selector",
                    "fieldContext": "config.customOptions",
                    "fieldGroup": None,
                    "fieldClass": None,
                    "fieldAddOn": None,
                    "fieldComponent": None,
                    "fieldInput": None,
                    "placeHolder": None,
                    "verifyPattern": None,
                    "helpBlock": None,
                    "helpBlockFieldCode": None,
                    "defaultValue": "\"\"",
                    "optionSource": None,
                    "optionSourceType": None,
                    "optionList": None,
                    "type": "diskManager",
                    "advanced": False,
                    "required": False,
                    "exportMeta": False,
                    "editable": False,
                    "creatable": True,
                    "config": {
                        "poolFieldType": "field",
                        "poolField": "",
                        "enableStorageTypeSelection": True,
                        "addon": "",
                        "addonPosition": "",
                        "defaultValue": "[]",
                        "groupId": "",
                        "groupFieldType": "field",
                        "enableDiskTypeSelection": False,
                        "layoutId": "",
                        "groupField": "group_selector",
                        "layoutField": "layout_selector",
                        "cloudField": "cloud_selector",
                        "cloudId": "",
                        "poolId": "",
                        "enableDatastoreSelection": False,
                        "planId": "",
                        "cloudFieldType": "field",
                        "planFieldType": "field",
                        "planField": "plan_selector",
                        "layoutFieldType": "field"
                    },
                    "displayOrder": 0,
                    "wrapperClass": None,
                    "enabled": True,
                    "noBlank": False,
                    "dependsOnCode": None,
                    "visibleOnCode": None,
                    "requireOnCode": None,
                    "contextualDefault": False,
                    "displayValueOnDetails": False,
                    "showOnCreate": True,
                    "showOnEdit": True,
                    "localCredential": False,
                    "formField": True,
                    "isHidden": False,
                    "isLocked": False,
                    "minVal": None,
                    "maxVal": None
                }
            ]
        },
        {
            "name": "Network Configuration",
            "code": "step-3",
            "description": None,
            "localizedName": None,
            "collapsible": False,
            "defaultCollapsed": False,
            "visibleOnCode": None,
            "options": [
                {
                    "name": "Network",
                    "description": None,
                    "code": "network_selector",
                    "excludeFromSearch": False,
                    "fieldName": "network_selection",
                    "fieldLabel": "Network:",
                    "fieldCode": None,
                    "refCode": "network_selector",
                    "fieldContext": "config.customOptions",
                    "fieldGroup": None,
                    "fieldClass": None,
                    "fieldAddOn": None,
                    "fieldComponent": None,
                    "fieldInput": None,
                    "placeHolder": None,
                    "verifyPattern": None,
                    "helpBlock": None,
                    "helpBlockFieldCode": None,
                    "defaultValue": "\"\"",
                    "optionSource": None,
                    "optionSourceType": None,
                    "optionList": None,
                    "type": "networkManager",
                    "advanced": False,
                    "required": False,
                    "exportMeta": False,
                    "editable": False,
                    "creatable": True,
                    "config": {
                        "poolFieldType": "field",
                        "poolField": "resourcePool_selector",
                        "addon": "",
                        "addonPosition": "right",
                        "defaultValue": "[]",
                        "groupId": "",
                        "groupFieldType": "field",
                        "layoutId": "",
                        "groupField": "group_selector",
                        "layoutField": "layout_selector",
                        "cloudField": "cloud_selector",
                        "enableIPModeSelection": True,
                        "showNetworkTypeSelection": True,
                        "cloudId": "",
                        "poolId": "",
                        "planId": "",
                        "cloudFieldType": "field",
                        "layoutFieldType": "field",
                        "planField": "plan_selector",
                        "planFieldType": "field"
                    },
                    "displayOrder": 0,
                    "wrapperClass": None,
                    "enabled": True,
                    "noBlank": False,
                    "dependsOnCode": None,
                    "visibleOnCode": None,
                    "requireOnCode": None,
                    "contextualDefault": False,
                    "displayValueOnDetails": False,
                    "showOnCreate": True,
                    "showOnEdit": True,
                    "localCredential": False,
                    "formField": True,
                    "isHidden": False,
                    "isLocked": False,
                    "minVal": None,
                    "maxVal": None
                },
                {
                    "name": "Security Group",
                    "description": None,
                    "code": "security_group_selector",
                    "excludeFromSearch": False,
                    "fieldName": "security_group_selection",
                    "fieldLabel": "Security Group:",
                    "fieldCode": None,
                    "refCode": "security_group_selector",
                    "fieldContext": "config.customOptions",
                    "fieldGroup": None,
                    "fieldClass": None,
                    "fieldAddOn": None,
                    "fieldComponent": None,
                    "fieldInput": None,
                    "placeHolder": None,
                    "verifyPattern": None,
                    "helpBlock": None,
                    "helpBlockFieldCode": None,
                    "defaultValue": "\"\"",
                    "optionSource": None,
                    "optionSourceType": None,
                    "optionList": None,
                    "type": "secGroup",
                    "advanced": False,
                    "required": False,
                    "exportMeta": False,
                    "editable": False,
                    "creatable": True,
                    "config": {
                        "cloudField": "cloud_selector",
                        "resourcePoolField": "resourcePool_selector",
                        "addon": "",
                        "addonPosition": "",
                        "defaultValue": "\"\"",
                        "cloudId": "",
                        "cloudFieldType": "field"
                    },
                    "displayOrder": 1,
                    "wrapperClass": None,
                    "enabled": True,
                    "noBlank": False,
                    "dependsOnCode": None,
                    "visibleOnCode": None,
                    "requireOnCode": None,
                    "contextualDefault": False,
                    "displayValueOnDetails": False,
                    "showOnCreate": True,
                    "showOnEdit": True,
                    "localCredential": False,
                    "formField": True,
                    "isHidden": False,
                    "isLocked": False,
                    "minVal": None,
                    "maxVal": None
                }
            ]
        }
    ],
    "options": [
        {
            "name": "Group",
            "description": None,
            "code": "group_selector",
            "excludeFromSearch": False,
            "fieldName": "group_selection_",
            "fieldLabel": "Group:",
            "fieldCode": None,
            "refCode": "group_selector",
            "fieldContext": "config.customOptions",
            "fieldGroup": None,
            "fieldClass": None,
            "fieldAddOn": None,
            "fieldComponent": None,
            "fieldInput": None,
            "placeHolder": None,
            "verifyPattern": None,
            "helpBlock": None,
            "helpBlockFieldCode": None,
            "defaultValue": "1",
            "optionSource": None,
            "optionSourceType": None,
            "optionList": None,
            "type": "group",
            "advanced": False,
            "required": False,
            "exportMeta": False,
            "editable": False,
            "creatable": True,
            "config": {
                "addon": "",
                "addonPosition": ""
            },
            "displayOrder": 0,
            "wrapperClass": None,
            "enabled": True,
            "noBlank": False,
            "dependsOnCode": None,
            "visibleOnCode": None,
            "requireOnCode": None,
            "contextualDefault": False,
            "displayValueOnDetails": False,
            "showOnCreate": True,
            "showOnEdit": True,
            "localCredential": False,
            "formField": True,
            "isHidden": False,
            "isLocked": False,
            "minVal": None,
            "maxVal": None
        },
        {
            "name": "Cloud",
            "description": None,
            "code": "cloud_selector",
            "excludeFromSearch": False,
            "fieldName": "cloud_selection_",
            "fieldLabel": "Cloud:",
            "fieldCode": None,
            "refCode": "cloud_selector",
            "fieldContext": "config.customOptions",
            "fieldGroup": None,
            "fieldClass": None,
            "fieldAddOn": None,
            "fieldComponent": None,
            "fieldInput": None,
            "placeHolder": None,
            "verifyPattern": None,
            "helpBlock": None,
            "helpBlockFieldCode": None,
            "defaultValue": None,
            "optionSource": None,
            "optionSourceType": None,
            "optionList": None,
            "type": "cloud",
            "advanced": False,
            "required": False,
            "exportMeta": False,
            "editable": False,
            "creatable": True,
            "config": {
                "filterResource": False,
                "addon": "",
                "addonPosition": "",
                "cloudType": "",
                "instanceTypeCode": "ubuntu",
                "groupId": "",
                "instanceTypeFieldCode": "",
                "groupFieldType": "field",
                "instanceTypeFieldType": "value",
                "group": "group_selector"
            },
            "displayOrder": 1,
            "wrapperClass": None,
            "enabled": True,
            "noBlank": False,
            "dependsOnCode": "group_selection_",
            "visibleOnCode": None,
            "requireOnCode": None,
            "contextualDefault": False,
            "displayValueOnDetails": False,
            "showOnCreate": True,
            "showOnEdit": True,
            "localCredential": False,
            "formField": True,
            "isHidden": False,
            "isLocked": False,
            "minVal": None,
            "maxVal": None
        },
        {
            "name": "Resource Pool",
            "description": None,
            "code": "resourcePool_selector",
            "excludeFromSearch": False,
            "fieldName": "resource_pool_selection",
            "fieldLabel": "Resource Pool:",
            "fieldCode": None,
            "refCode": "resourcePool_selector",
            "fieldContext": "config.customOptions",
            "fieldGroup": None,
            "fieldClass": None,
            "fieldAddOn": None,
            "fieldComponent": None,
            "fieldInput": None,
            "placeHolder": None,
            "verifyPattern": None,
            "helpBlock": None,
            "helpBlockFieldCode": None,
            "defaultValue": None,
            "optionSource": None,
            "optionSourceType": None,
            "optionList": None,
            "type": "resourcePool",
            "advanced": False,
            "required": False,
            "exportMeta": False,
            "editable": False,
            "creatable": True,
            "config": {
                "addonPosition": "",
                "groupId": "",
                "groupFieldType": "field",
                "layoutId": "",
                "groupField": "group_selector",
                "layoutField": "layout_selector",
                "cloudField": "cloud_selector",
                "cloudId": "",
                "planId": "",
                "cloudFieldType": "field",
                "layoutFieldType": "field",
                "planField": "plan_selector",
                "planFieldType": "field"
            },
            "displayOrder": 2,
            "wrapperClass": None,
            "enabled": True,
            "noBlank": False,
            "dependsOnCode": None,
            "visibleOnCode": None,
            "requireOnCode": None,
            "contextualDefault": False,
            "displayValueOnDetails": False,
            "showOnCreate": True,
            "showOnEdit": True,
            "localCredential": False,
            "formField": True,
            "isHidden": False,
            "isLocked": False,
            "minVal": None,
            "maxVal": None
        },
        {
            "name": "b43561f3-1677-4367-85e6-11fbbe671127",
            "description": None,
            "code": "b43561f3-1677-4367-85e6-11fbbe671127",
            "excludeFromSearch": False,
            "fieldName": "folderSelector",
            "fieldLabel": "Folder:",
            "fieldCode": None,
            "refCode": "b43561f3-1677-4367-85e6-11fbbe671127",
            "fieldContext": "config.customOptions",
            "fieldGroup": None,
            "fieldClass": None,
            "fieldAddOn": None,
            "fieldComponent": None,
            "fieldInput": None,
            "placeHolder": None,
            "verifyPattern": None,
            "helpBlock": None,
            "helpBlockFieldCode": None,
            "defaultValue": "0",
            "optionSource": None,
            "optionSourceType": None,
            "optionList": None,
            "type": "vmwFolders",
            "advanced": False,
            "required": False,
            "exportMeta": False,
            "editable": False,
            "creatable": True,
            "config": {
                "groupField": "group_selector",
                "cloudField": "cloud_selector",
                "addon": "",
                "addonPosition": "",
                "groupId": "",
                "cloudId": "",
                "planId": "",
                "groupFieldType": "field",
                "cloudFieldType": "field",
                "planFieldType": "field",
                "planField": "plan_selector"
            },
            "displayOrder": 3,
            "wrapperClass": None,
            "enabled": True,
            "noBlank": False,
            "dependsOnCode": None,
            "visibleOnCode": None,
            "requireOnCode": None,
            "contextualDefault": False,
            "displayValueOnDetails": False,
            "showOnCreate": True,
            "showOnEdit": True,
            "localCredential": False,
            "formField": True,
            "isHidden": False,
            "isLocked": False,
            "minVal": None,
            "maxVal": None
        }
    ]
}}
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer <MORPHEUS_API_TOKEN>"                                      # change me :)
}

response = requests.request("POST", url, json=payload, headers=headers, params=querystring, verify=False)

print(response.text)
