import requests

url = "<MORPHEUS_APPLIANCE_URL>/api/library/option-type-forms"                                     # change me :)

querystring = {"":""}

payload = {"optionTypeForm": {
        "name": "New Test Form",
        "description": "A simple test form",
        "code": "new_test_form",
        "config": {},
        "context": None,
        "isLocked": False,
        "labels": "",
        "fieldGroups": [
            {
                "name": "Layout + Plan selection",
                "description": None,
                "localizedName": None,
                "collapsible": False,
                "defaultCollapsed": False,
                "visibleOnCode": None,
                "options": [
                    {
                        "name": "Layout",
                        "description": None,
                        "code": "layout_selector",
                        "excludeFromSearch": False,
                        "fieldName": "layout_selection_",
                        "fieldLabel": "Layout:",
                        "fieldCode": None,
                        "refCode": "layout_selector",
                        "fieldContext": "config.customOptions",
                        "fieldGroup": None,
                        "fieldClass": None,
                        "fieldAddOn": None,
                        "fieldComponent": None,
                        "fieldInput": None,
                        "placeHolder": None,
                        "verifyPattern": None,
                        "helpBlock": None,
                        "helpBlockFieldCode": None,
                        "defaultValue": None,
                        "optionSource": None,
                        "optionSourceType": None,
                        "optionList": None,
                        "type": "layout",
                        "advanced": False,
                        "required": False,
                        "exportMeta": False,
                        "editable": False,
                        "creatable": True,
                        "config": {
                            "groupField": "group_selector",
                            "cloudField": "cloud_selector",
                            "addonPosition": "",
                            "instanceTypeCode": "ubuntu",
                            "groupId": "",
                            "cloudId": "",
                            "instanceTypeFieldCode": "",
                            "groupFieldType": "field",
                            "cloudFieldType": "field",
                            "instanceTypeFieldType": "value"
                        },
                        "displayOrder": 0,
                        "wrapperClass": None,
                        "enabled": True,
                        "noBlank": False,
                        "dependsOnCode": None,
                        "visibleOnCode": None,
                        "requireOnCode": None,
                        "contextualDefault": False,
                        "displayValueOnDetails": False,
                        "showOnCreate": True,
                        "showOnEdit": True,
                        "localCredential": False,
                        "formField": True,
                        "isHidden": False,
                        "isLocked": False,
                        "minVal": None,
                        "maxVal": None
                    },
                    {
                        "name": "Plan",
                        "description": None,
                        "code": "plan_selector",
                        "excludeFromSearch": False,
                        "fieldName": "plan_selection_",
                        "fieldLabel": "Plan:",
                        "fieldCode": None,
                        "refCode": "plan_selector",
                        "fieldContext": "config.customOptions",
                        "fieldGroup": None,
                        "fieldClass": None,
                        "fieldAddOn": None,
                        "fieldComponent": None,
                        "fieldInput": None,
                        "placeHolder": None,
                        "verifyPattern": None,
                        "helpBlock": None,
                        "helpBlockFieldCode": None,
                        "defaultValue": None,
                        "optionSource": None,
                        "optionSourceType": None,
                        "optionList": None,
                        "type": "plan",
                        "advanced": False,
                        "required": False,
                        "exportMeta": False,
                        "editable": False,
                        "creatable": True,
                        "config": {
                            "poolFieldType": "field",
                            "poolField": "resourcePool_selector",
                            "defaultValue": "{}",
                            "groupId": "",
                            "groupFieldType": "field",
                            "layoutId": "",
                            "groupField": "group_selector",
                            "layoutField": "layout_selector",
                            "showPricing": False,
                            "cloudField": "cloud_selector",
                            "cloudId": "",
                            "poolId": "",
                            "diskField": "",
                            "cloudFieldType": "field",
                            "layoutFieldType": "field"
                        },
                        "displayOrder": 1,
                        "wrapperClass": None,
                        "enabled": True,
                        "noBlank": False,
                        "dependsOnCode": None,
                        "visibleOnCode": None,
                        "requireOnCode": None,
                        "contextualDefault": False,
                        "displayValueOnDetails": False,
                        "showOnCreate": True,
                        "showOnEdit": True,
                        "localCredential": False,
                        "formField": True,
                        "isHidden": False,
                        "isLocked": False,
                        "minVal": None,
                        "maxVal": None
                    }
                ]
            },
            {
                "name": "Network Configuration",
                "description": None,
                "localizedName": None,
                "collapsible": False,
                "defaultCollapsed": False,
                "visibleOnCode": None,
                "options": [
                    {
                        "name": "Network",
                        "description": None,
                        "code": "network_selector",
                        "excludeFromSearch": False,
                        "fieldName": "network_selection",
                        "fieldLabel": "Network:",
                        "fieldCode": None,
                        "refCode": "network_selector",
                        "fieldContext": "config.customOptions",
                        "fieldGroup": None,
                        "fieldClass": None,
                        "fieldAddOn": None,
                        "fieldComponent": None,
                        "fieldInput": None,
                        "placeHolder": None,
                        "verifyPattern": None,
                        "helpBlock": None,
                        "helpBlockFieldCode": None,
                        "defaultValue": "\"\"",
                        "optionSource": None,
                        "optionSourceType": None,
                        "optionList": None,
                        "type": "networkManager",
                        "advanced": False,
                        "required": False,
                        "exportMeta": False,
                        "editable": False,
                        "creatable": True,
                        "config": {
                            "poolFieldType": "field",
                            "poolField": "resourcePool_selector",
                            "addon": "",
                            "addonPosition": "",
                            "defaultValue": "[]",
                            "groupId": "",
                            "groupFieldType": "field",
                            "layoutId": "",
                            "groupField": "group_selector",
                            "layoutField": "layout_selector",
                            "cloudField": "cloud_selector",
                            "enableIPModeSelection": False,
                            "showNetworkTypeSelection": False,
                            "cloudId": "",
                            "poolId": "",
                            "planId": "",
                            "cloudFieldType": "field",
                            "planFieldType": "field",
                            "planField": "plan_selector",
                            "layoutFieldType": "field"
                        },
                        "displayOrder": 0,
                        "wrapperClass": None,
                        "enabled": True,
                        "noBlank": False,
                        "dependsOnCode": None,
                        "visibleOnCode": None,
                        "requireOnCode": None,
                        "contextualDefault": False,
                        "displayValueOnDetails": False,
                        "showOnCreate": True,
                        "showOnEdit": True,
                        "localCredential": False,
                        "formField": True,
                        "isHidden": False,
                        "isLocked": False,
                        "minVal": None,
                        "maxVal": None
                    },
                    {
                        "name": "Security Group",
                        "description": None,
                        "code": "security_group_selector",
                        "excludeFromSearch": False,
                        "fieldName": "security_group_selection",
                        "fieldLabel": "Security Group:",
                        "fieldCode": None,
                        "refCode": "security_group_selector",
                        "fieldContext": "config.customOptions",
                        "fieldGroup": None,
                        "fieldClass": None,
                        "fieldAddOn": None,
                        "fieldComponent": None,
                        "fieldInput": None,
                        "placeHolder": None,
                        "verifyPattern": None,
                        "helpBlock": None,
                        "helpBlockFieldCode": None,
                        "defaultValue": "\"\"",
                        "optionSource": None,
                        "optionSourceType": None,
                        "optionList": None,
                        "type": "secGroup",
                        "advanced": False,
                        "required": False,
                        "exportMeta": False,
                        "editable": False,
                        "creatable": True,
                        "config": {
                            "cloudField": "cloud_selector",
                            "resourcePoolField": "resourcePool_selector",
                            "addon": "",
                            "addonPosition": "",
                            "defaultValue": "\"\"",
                            "cloudId": "",
                            "cloudFieldType": "field"
                        },
                        "displayOrder": 1,
                        "wrapperClass": None,
                        "enabled": True,
                        "noBlank": False,
                        "dependsOnCode": None,
                        "visibleOnCode": None,
                        "requireOnCode": None,
                        "contextualDefault": False,
                        "displayValueOnDetails": False,
                        "showOnCreate": True,
                        "showOnEdit": True,
                        "localCredential": False,
                        "formField": True,
                        "isHidden": False,
                        "isLocked": False,
                        "minVal": None,
                        "maxVal": None
                    }
                ]
            }
        ],
        "options": [
            {
                "name": "Group",
                "description": None,
                "code": "group_selector",
                "excludeFromSearch": False,
                "fieldName": "group_selection_",
                "fieldLabel": "Group:",
                "fieldCode": None,
                "refCode": "group_selector",
                "fieldContext": "config.customOptions",
                "fieldGroup": None,
                "fieldClass": None,
                "fieldAddOn": None,
                "fieldComponent": None,
                "fieldInput": None,
                "placeHolder": None,
                "verifyPattern": None,
                "helpBlock": None,
                "helpBlockFieldCode": None,
                "defaultValue": "3",
                "optionSource": None,
                "optionSourceType": None,
                "optionList": None,
                "type": "group",
                "advanced": False,
                "required": False,
                "exportMeta": False,
                "editable": False,
                "creatable": True,
                "config": {
                    "addon": "",
                    "addonPosition": ""
                },
                "displayOrder": 0,
                "wrapperClass": None,
                "enabled": True,
                "noBlank": False,
                "dependsOnCode": None,
                "visibleOnCode": None,
                "requireOnCode": None,
                "contextualDefault": False,
                "displayValueOnDetails": False,
                "showOnCreate": True,
                "showOnEdit": True,
                "localCredential": False,
                "formField": True,
                "isHidden": False,
                "isLocked": False,
                "minVal": None,
                "maxVal": None
            },
            {
                "name": "Cloud",
                "description": None,
                "code": "cloud_selector",
                "excludeFromSearch": False,
                "fieldName": "cloud_selection_",
                "fieldLabel": "Cloud:",
                "fieldCode": None,
                "refCode": "cloud_selector",
                "fieldContext": "config.customOptions",
                "fieldGroup": None,
                "fieldClass": None,
                "fieldAddOn": None,
                "fieldComponent": None,
                "fieldInput": None,
                "placeHolder": None,
                "verifyPattern": None,
                "helpBlock": None,
                "helpBlockFieldCode": None,
                "defaultValue": None,
                "optionSource": None,
                "optionSourceType": None,
                "optionList": None,
                "type": "cloud",
                "advanced": False,
                "required": False,
                "exportMeta": False,
                "editable": False,
                "creatable": True,
                "config": {
                    "filterResource": False,
                    "addon": "",
                    "addonPosition": "",
                    "instanceTypeCode": "ubuntu",
                    "cloudType": "",
                    "groupId": "",
                    "instanceTypeFieldCode": "",
                    "groupFieldType": "field",
                    "instanceTypeFieldType": "value",
                    "group": "group_selector"
                },
                "displayOrder": 1,
                "wrapperClass": None,
                "enabled": True,
                "noBlank": False,
                "dependsOnCode": "group_selection_",
                "visibleOnCode": None,
                "requireOnCode": None,
                "contextualDefault": False,
                "displayValueOnDetails": False,
                "showOnCreate": True,
                "showOnEdit": True,
                "localCredential": False,
                "formField": True,
                "isHidden": False,
                "isLocked": False,
                "minVal": None,
                "maxVal": None
            },
            {
                "name": "Resource Pool",
                "description": None,
                "code": "resourcePool_selector",
                "excludeFromSearch": False,
                "fieldName": "resource_pool_selection",
                "fieldLabel": "Resource Pool:",
                "fieldCode": None,
                "refCode": "resourcePool_selector",
                "fieldContext": "config.customOptions",
                "fieldGroup": None,
                "fieldClass": None,
                "fieldAddOn": None,
                "fieldComponent": None,
                "fieldInput": None,
                "placeHolder": None,
                "verifyPattern": None,
                "helpBlock": None,
                "helpBlockFieldCode": None,
                "defaultValue": "\"\"",
                "optionSource": None,
                "optionSourceType": None,
                "optionList": None,
                "type": "resourcePool",
                "advanced": False,
                "required": False,
                "exportMeta": False,
                "editable": False,
                "creatable": True,
                "config": {
                    "addonPosition": "",
                    "groupId": "",
                    "groupFieldType": "field",
                    "layoutId": "",
                    "groupField": "group_selector",
                    "layoutField": "layout_selector",
                    "cloudField": "cloud_selector",
                    "cloudId": "",
                    "planId": "",
                    "cloudFieldType": "field",
                    "planFieldType": "field",
                    "planField": "plan_selector",
                    "layoutFieldType": "field"
                },
                "displayOrder": 2,
                "wrapperClass": None,
                "enabled": True,
                "noBlank": False,
                "dependsOnCode": None,
                "visibleOnCode": None,
                "requireOnCode": None,
                "contextualDefault": False,
                "displayValueOnDetails": False,
                "showOnCreate": True,
                "showOnEdit": True,
                "localCredential": False,
                "formField": True,
                "isHidden": False,
                "isLocked": False,
                "minVal": None,
                "maxVal": None
            }
        ]
    }}
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer <MORPHEUS_API_TOKEN>"                                      # change me :)
}

response = requests.request("POST", url, json=payload, headers=headers, params=querystring, verify=False)

print(response.text)
